const express = require('express');
const cors = require('cors');
require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const { GoogleGenAI } = require('@google/genai');

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY;
const supabase = (supabaseUrl && supabaseKey) ? createClient(supabaseUrl, supabaseKey) : null;

const ai = process.env.GEMINI_API_KEY ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }) : null;

app.get('/api/health', (req, res) => {
    res.json({
            status: "ok",
                    message: "Hostel HQ AI Assistant Backend is live!",
                            services: { supabase_connected: !!supabase, gemini_connected: !!ai }
                                });
                                });

                                // --- THE RAG CHAT ENDPOINT WITH AUTO-RETRY ---
                                app.post('/api/chat', async (req, res) => {
                                    try {
                                            const { message } = req.body;
                                                    if (!message) {
                                                                return res.status(400).json({ error: "Message is required" });
                                                                        }

                                                                                let retrievedContext = "";

                                                                                        // 1. Try vector similarity search
                                                                                                try {
                                                                                                            if (ai && supabase) {
                                                                                                                            const embeddingResponse = await ai.models.embedContent({
                                                                                                                                                model: 'text-embedding-004',
                                                                                                                                                                    contents: message,
                                                                                                                                                                                    });
                                                                                                                                                                                                    
                                                                                                                                                                                                                    const queryEmbedding = embeddingResponse.embedding.values;

                                                                                                                                                                                                                                    const { data: vectorMatches } = await supabase.rpc('match_documents', {
                                                                                                                                                                                                                                                        query_embedding: queryEmbedding,
                                                                                                                                                                                                                                                                            match_threshold: 0.3,
                                                                                                                                                                                                                                                                                                match_count: 4
                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                if (vectorMatches && vectorMatches.length > 0) {
                                                                                                                                                                                                                                                                                                                                                    retrievedContext = vectorMatches.map(item => item.content).join("\n\n");
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        } catch (embErr) {
                                                                                                                                                                                                                                                                                                                                                                                                    console.log("Vector search skipped or failed, using text fallback...", embErr.message);
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                    // 2. FALLBACK: If vector search found nothing, search text columns directly
                                                                                                                                                                                                                                                                                                                                                                                                                            if (!retrievedContext && supabase) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data: textMatches } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .from('hostel_knowledge')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .select('content')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .ilike('content', `%${message}%`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .limit(3);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (textMatches && textMatches.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    retrievedContext = textMatches.map(item => item.content).join("\n\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Generate response with Gemini using auto-retry for 503 spikes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const prompt = `You are Hostel HQ Assistant, an expert campus guide. Answer the user's question accurately using ONLY the provided context below. If the answer is not in the context, politely state that you do not have the information.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Context:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${retrievedContext || "No specific context found."}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        User Question: ${message}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let reply = "I apologize, but I do not have that information based on the provided context.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (ai) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let attempts = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let success = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (attempts < 3 && !success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    attempts++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const aiResponse = await ai.models.generateContent({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                model: 'gemini-3.5-flash', // Using highly stable flash endpoint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        contents: prompt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reply = aiResponse.text || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                aiResponse.candidates?.[0]?.content?.parts?.[0]?.text || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reply;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (apiErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const isOverloaded = apiErr.status === 503 || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             apiErr.message?.includes('503') || 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      apiErr.message?.includes('high demand') ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               apiErr.message?.includes('UNAVAILABLE');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isOverloaded && attempts < 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Gemini overloaded (Attempt ${attempts}), retrying in 2 seconds...`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await new Promise(resolve => setTimeout(resolve, 2000));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw apiErr;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ answer: reply, reply: reply });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error("Chat Error:", error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({ error: error.message || "Failed to process chat request" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // --- SERVER LISTENER ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.listen(port, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Hostel HQ Server running on port ${port}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    